# -*- coding: utf-8 -*-
"""Taller#4_Alejandra_Arteaga

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiGE3uF_qhXUEC72z8ztBaNiv8EYopUY

# Taller #4

## Alejandra Arteaga Robalino

#### **Descripción del taller:** El siguiente dashboard permite al gerente de Foodie's Place explorar el comportamiento de las propinas según el día de la semana y el momento de la comida (almuerzo o cena), con el objetivo de validar si la cena y los fines de semana generan mayores ingresos para el equipo de camareros.

### Importar las librerías

streamlit  → construcción de la aplicación web interactiva

plotly.express → visualizaciones interactivas con sintaxis simplificada

pandas → manipulación y agrupación del dataframe
"""

import subprocess
import sys
subprocess.run([sys.executable, "-m", "pip", "install", "streamlit", "plotly", "pandas"])

"""### Diseñar la página de Streamlit

Se define el título que aparece en la pestaña del navegador,
el ícono de la aplicación y el layout "wide" para aprovechar todo el ancho de la pantalla en el dashboard.
"""

st.set_page_config(
    page_title="Foodie's Place Dashboard",
    page_icon="🍽️",
    layout="wide"
)

"""### Selección y carga de base de datos (base de datos parte de la biblioteca)

El dataset "tips" viene integrado en Plotly Express y contiene
244 registros de propinas registradas en un restaurante.
Variables principales:
 - total_bill : monto total de la cuenta (USD)
 - tip        : monto de la propina (USD)
 - sex        : género del cliente que paga
 - day        : día de la semana (Thur, Fri, Sat, Sun)
 - time       : momento de la comida (Lunch / Dinner)
 - size       : número de personas en la mesa
"""

tips = px.data.tips()

"""### Encabezado de la hoja

Título y descripción del propósito del dashboard.Se usa st.divider() para separar visualmente el encabezado del resto del contenido.
"""

st.title("🍽️ Foodie's Place — Dashboard de Propinas")
st.markdown(
    "Análisis exploratorio para validar si **la cena genera más propinas que el almuerzo** "
    "y si **los fines de semana superan a los días laborables**."
)
st.divider()

"""### Agregar filtros para definir el día y el tiempo en el que tiene lugar

La barra lateral contiene los controles que permiten al gerente
segmentar los datos sin modificar el código.

Filtro 1 — Día de la semana:
 Multiselect que toma los valores únicos del campo "day".
 Por defecto todos los días están seleccionados para mostrar
 el panorama completo al abrir el dashboard.

 Filtro 2 — Momento del día:
Multiselect sobre el campo "time" (Lunch / Dinner). Permite aislar el análisis a solo un momento si se desea.
"""

st.sidebar.title("🔍 Filtros")

# Se selecciona por defecto
dias_disponibles = tips["day"].unique().tolist()
dias_seleccionados = st.sidebar.multiselect(
    label="Selecciona el Día",
    options=dias_disponibles,
    default=dias_disponibles
)

"""### Agregar filtros para definir la hora en el día"""

momentos_disponibles = tips["time"].unique().tolist()
momentos_seleccionados = st.sidebar.multiselect(
    label="Selecciona el Momento",
    options=momentos_disponibles,
    default=momentos_disponibles
)

st.sidebar.markdown("---")
st.sidebar.markdown("📊 **Fuente:** Dataset `tips` — Plotly Express")

"""### Se aplican los filtros en el Sidebar

Se genera un nuevo dataframe (df_filtrado) aplicando las selecciones del sidebar con isin(), de modo que todos los gráficos y métricas reaccionen automáticamente a los filtros.

Si la combinación de filtros resulta en un dataframe vacío, se muestra una advertencia y se detiene la ejecución para evitar errores en los gráficos.
"""

df_filtrado = tips[
    (tips["day"].isin(dias_seleccionados)) &
    (tips["time"].isin(momentos_seleccionados))
]

# Aviso si no hay datos con los filtros aplicados
if df_filtrado.empty:
    st.warning("⚠️ No hay datos para los filtros seleccionados. Ajusta los filtros en el sidebar.")
    st.stop()

"""### KPIs

Se muestran 3 indicadores en la parte superior del dashboard
usando st.columns para distribuirlos en una fila horizontal. Cada métrica se calcula sobre el dataframe ya filtrado, por lo que se actualiza en tiempo real con cada cambio en el sidebar.

 col_kpi1 → Total Facturado  : suma de total_bill
 col_kpi2 → Total Propinas   : suma de tip
 col_kpi3 → Propina Promedio : media de tip

Los valores se formatean como moneda (${valor:,.2f}) para facilitar la lectura gerencial.
"""

st.subheader("📌 Métricas Clave")

col_kpi1, col_kpi2, col_kpi3 = st.columns(3)

with col_kpi1:
    total_facturado = df_filtrado["total_bill"].sum()
    st.metric(
        label="💵 Total Facturado",
        value=f"${total_facturado:,.2f}"
    )

with col_kpi2:
    total_propinas = df_filtrado["tip"].sum()
    st.metric(
        label="💰 Total Propinas",
        value=f"${total_propinas:,.2f}"
    )

with col_kpi3:
    propina_promedio = df_filtrado["tip"].mean()
    st.metric(
        label="📈 Propina Promedio",
        value=f"${propina_promedio:,.2f}"
    )

st.divider()

"""### Gráfico de barras que refleje ¿En qué momento del día se generan más propinas?

Columna izquierda: Total de Propinas por Momento del Día -
Pregunta de negocio: ¿La cena genera más propinas que el almuerzo?

Se agrupa df_filtrado por "time" y se suman las propinas. Se usa un gráfico de barras con colores diferenciados:
  - Naranja (#E07B39) para Dinner
  - Azul    (#4A90D9) para Lunch

El valor se muestra encima de cada barra con text_auto.
"""

st.subheader("📊 Visualizaciones")

col_izq, col_der = st.columns(2)

# ── Columna izquierda: Total de Propinas por Momento del Día ──
with col_izq:
    st.markdown("**¿Se gana más en la Cena o en el Almuerzo?**")

    # Agrupamos las propinas totales por momento del día
    propinas_por_momento = (
        df_filtrado.groupby("time", as_index=False)["tip"]
        .sum()
        .rename(columns={"tip": "Total Propinas", "time": "Momento"})
    )

    fig_bar = px.bar(
        propinas_por_momento,
        x="Momento",
        y="Total Propinas",
        color="Momento",
        text_auto=".2f",
        color_discrete_map={"Dinner": "#E07B39", "Lunch": "#4A90D9"},
        title="Total de Propinas por Momento del Día",
        labels={"Total Propinas": "Total ($)", "Momento": "Momento del Día"}
    )
    fig_bar.update_traces(textposition="outside")
    fig_bar.update_layout(showlegend=False, plot_bgcolor="rgba(0,0,0,0)")
    st.plotly_chart(fig_bar, use_container_width=True)

"""### Scatter Plot: Cuenta Total vs. Propina

Columna derecha: Scatter Plot Total Cuenta vs. Propina - Pregunta de negocio: ¿A mayor consumo, mayor propina?

Cada punto representa una transacción individual.
Codificación visual:
  - Color  → Momento del día (Dinner / Lunch)
  - Símbolo → Día de la semana
  - Tamaño → Número de personas en la mesa

Se agrega una línea de tendencia OLS (regresión lineal) con trendline="ols" para evidenciar la correlación positiva entre el monto de la cuenta y la propina recibida.
"""

with col_der:
    st.markdown("**¿A mayor consumo, mayor propina?**")

    fig_scatter = px.scatter(
        df_filtrado,
        x="total_bill",
        y="tip",
        color="time",
        symbol="day",
        size="size",
        hover_data=["sex", "day", "time", "size"],
        color_discrete_map={"Dinner": "#E07B39", "Lunch": "#4A90D9"},
        trendline="ols",              # línea de tendencia
        title="Total Cuenta vs. Propina",
        labels={
            "total_bill": "Total Cuenta ($)",
            "tip": "Propina ($)",
            "time": "Momento",
            "day": "Día"
        }
    )
    fig_scatter.update_layout(plot_bgcolor="rgba(0,0,0,0)")
    st.plotly_chart(fig_scatter, use_container_width=True)

"""### Insight Final y Conlusión

Se usa st.success() para presentar los hallazgos principales de forma clara y accionable para el gerente.

La conclusión responde directamente a la hipótesis planteada y agrega una recomendación estratégica basada en los datos.
"""

st.divider()
st.subheader("💡 Conclusión de Negocio")

st.success(
    "✅ **Los datos respaldan la teoría del gerente:**\n\n"
    "- 🌙 **La cena supera al almuerzo** en propinas totales. Los clientes de cena generan "
    "consistentemente mayores montos de propina, probablemente porque las cuentas son más altas.\n\n"
    "- 📅 **El fin de semana (Sat & Sun) concentra la mayor actividad** y mayores propinas acumuladas "
    "frente a los días entre semana (Thur & Fri).\n\n"
    "- 📈 **Existe una correlación positiva** entre el total de la cuenta y la propina: "
    "a mayor consumo, mayor propina — lo que sugiere que incentivar órdenes más grandes "
    "(postres, bebidas) puede impactar directamente los ingresos del equipo de camareros.\n\n"
    "**Recomendación:** Reforzar el personal en cenas de fin de semana y capacitar al equipo "
    "en upselling para maximizar el ticket promedio."
)

"""## Referencias

Streamlit:

Streamlit Inc. (2024). Streamlit documentation. https://docs.streamlit.io

Plotly Express:

Plotly Technologies Inc. (2024). Plotly Express documentation. https://plotly.com/python/plotly-express/

Dataset tips:

Bryant, P. G., & Smith, M. A. (1995). Practical data analysis: Case studies in business statistics. Irwin. [Dataset distribuido a través de plotly.express.data.tips()]

Pandas:

McKinney, W., & the Pandas Development Team. (2024). pandas: Powerful Python data analysis toolkit (versión 2.x). https://pandas.pydata.org/docs/
"""